# Generated by Django 5.2.17 on 2026-09-07 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completionevent',
            options={'ordering': ['-completed_at', '-id']},
        ),
    ]
