# Generated by Django 5.2.17 on 2026-09-07 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_alter_completionevent_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='recurrence',
            field=models.CharField(choices=[('NONE', 'Does not repeat'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Every 2 weeks'), ('MONTHLY', 'Monthly')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='chore',
            name='rotate_assignee',
            field=models.BooleanField(default=False, help_text='Pass each new occurrence to the next household member.'),
        ),
    ]
